name: Update Logos Database

on:
  push:
    paths:
      - 'logos/**'

jobs:
  update-logos-json:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Generate Logos JSON
      id: generate-json
      run: |
        # Crear directorio si no existe
        mkdir -p logos
        
        # Generar JSON con todas las imágenes
        echo "Generando logos.json..."
        echo '{' > logos.json
        
        # Buscar archivos de imagen y procesarlos
        first=true
        for file in logos/*; do
          if [ -f "$file" ]; then
            filename=$(basename -- "$file")
            channel_name="${filename%.*}"
            raw_url="https://raw.githubusercontent.com/$GITHUB_REPOSITORY/main/$file"
            
            if [ "$first" = false ]; then
              echo "," >> logos.json
            else
              first=false
            fi
            
            echo -n "  \"$channel_name\": \"$raw_url\"" >> logos.json
          fi
        done
        
        echo "" >> logos.json
        echo '}' >> logos.json
        
        # Contar elementos
        item_count=$(grep -c '"' logos.json || true)
        echo "Total de logos: $(( (item_count - 2) / 2 ))"
        
    - name: Show Generated JSON
      run: cat logos.json

    - name: Commit and Push Changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        
        # Verificar cambios
        git add logos.json
        git status
        
        if ! git diff-index --quiet HEAD --; then
          git commit -m "Actualizar base de datos de logos"
          git push
          echo "Changes pushed"
        else
          echo "No changes to commit"
        fi
